[INTERNAL][FIX] sap.uxap.ObjectPageLayout: control sample corrected
(1) The sample used to throw js error
    TypeError: cannot set property backToPage of undefined
(2) Undefined is this._splitContainer
(3) I decided to remove the logic, related to splitContainer
    instead of just checking if it is available,
    because I can not see what value adds to the sample.
(4) I checked that in most of our sample this logic exists,
    but there is a check if the this._splitCOntainer is available
(5) The issue has been sportted by our colleagues, who sent us a mail.

Change-Id: I9d94c7bb966a8bfd53f96ca690e9b1459330672d