[FIX] grunt connect config - properly set default port
on a mac `grunt test` previously failed with the following message:
```
Running "connect:src" (connect) task
Fatal error: port should be > 0 and < 65536: 0
```

Updated
- `grunt-contrib-connect` to `^0.10.1`
- `selenium-webdriver` to `2.46.1`

Fixes https://github.com/SAP/openui5/pull/398

Change-Id: Ic1bd2005543b2b8e8338c3d32e44e4b1d6cb8a87
(cherry picked from commit 64f5050e3ca956acea0be2ca0636f56caba69348)
CR-Id: 012006153200002755182015