[FIX] sap.ui.model.odata.v4.Context#doSetProperty: avoid TypeError...
TypeError: Cannot read properties of undefined (reading '@$ui5._')

PS1: red integration test, POC, TDD

cherry picked from commit 3029192d63002a0e913d6138643cb12a2cf703ac

Change-Id: Ib882e734616e3e80aeace59d2e6646dca7fe637b
BCP: 2270087626
CR-Id: 002075125800002684592022