[INTERNAL] cldr-openui5, Generator#generateLocaleFile: throw Error for not yet supported RTL characters
Test:
* npm run generate-cldr generate
** -> success
* insert the following into
C:...\openui5\tmp\cldr\cldr-numbers-modern\main\ar\numbers.json
              "1000-count-hugo": "\u2069",
* npm run generate-cldr generate
** -> you got an Error exception like:
Error: Unsupported RTL character \u2069 found for locale ar

PS1: POC
PS2: throw Error instead of warning log, add mocha test, review comments
PS3: review comments, treat also \u202e as unsupported and \u061c as supported
PS4: remove temporarily TODO, review comment SBE
PS5: review comments PKS

Change-Id: I933dc6c12b08747e5313cda1e100c460783feeb2
JIRA: CPOUI5MODELS-1514