[INTERNAL] sap.f.Shellbar: fix SVG path for CoPilot animation
Executing the unit test for the Shellbar controls in Chrome 80 shows
several occurrences of the following error in the console:

Error: <path> attribute d: Expected path command, "…-17.85, 102 0 z ;M
104 0 C 103.6…".

This error seems to be caused by the semicolon in the path string.

Change-Id: I6968edb9857db8a28b0a1f820caca0a22979bcbc