[INTERNAL] sap.ui.model.odata.v4.ODataContextBinding: fix relative binding issue
If you use a relative property two way binding in a relative context
binding which is in an absolute context binding and if you change the
value of that property you get an error:
Failed to update path
/SalesOrderList(SalesOrderID='0500004416')/SO_2_BP/PhoneNumber -
TypeError: fnLog is not a function

How to test:
http://localhost:8080/testsuite/test-resources/sap/ui/core/demokit/sample/common/index.html?component=odata.v4.SalesOrders&sap-ui-xx-noless=X&realOData=true&$direct=true
Select a Sales Order (with no Sales Order Items, as long as the service
is not fixed) and modify the Phone Number of the Business Partner in the
Sales Order Details section

PS1: red integration test
PS2: fix it

Change-Id: I49d576a7a8946ae28dbe2bb87221aa3e06614913
JIRA: FLPUISERVICES2014-2177